<?php

namespace IssuesBundle\Tests\Functional\DataFixtures;

use Doctrine\Common\DataFixtures\AbstractFixture;
use Doctrine\Common\DataFixtures\DependentFixtureInterface;
use Doctrine\Common\Persistence\ObjectManager;
use IssuesBundle\Entity\Issue;
use Symfony\Component\DependencyInjection\ContainerAwareInterface;
use Symfony\Component\DependencyInjection\ContainerInterface;

class LoadIssuesData extends AbstractFixture implements ContainerAwareInterface, DependentFixtureInterface
{
    /**
     * @var ContainerInterface
     */
    protected $container;

    /**
     * {@inheritdoc}
     */
    public function setContainer(ContainerInterface $container = null)
    {
        $this->container = $container;
    }

    public function load(ObjectManager $manager)
    {
        $issue = new Issue();

        $user = $this->getReference(LoadUserData::USER_FIRST_USERNAME);

        $manager->persist($user);

        if (!$user) {
            throw new \DomainException('Admin user not found, ensure that fixtures from UserBundle'
                .' are executed first.');
        }

        $organization = $user->getOrganization();

        $issue->setOrganization($organization);
        $issue->setOwner($user);

        $issue->setSummary('Example Issue for functional test');
        $issue->setCode('TEST444');
        $issue->setDescription('This is an example, autogenerated, issue.');
        $issue->setType(Issue::TYPE_STORY);
        //$issue->setPriority($this->getReference('priority_10'));
        $issue->setReporter($user);
        $issue->setAssignee($user);
        $issue->setCreatedAt(new \DateTime('now'));
        $issue->setUpdatedAt(new \DateTime('now'));

        $this->setReference('issue', $issue);

        $manager->persist($issue);

        $manager->flush();
    }

    public function getDependencies()
    {
        return [
            'IssuesBundle\Tests\Functional\DataFixtures\LoadUserData'
        ];
    }
}
