parameters:
    issues_bundle.import_export.entity: "IssuesBundle\Entity\Issue"

services:
    issues_bundle.importexport.template_fixture.issue:
        class: IssuesBundle\ImportExport\TemplateFixture\IssueFixture
        tags:
            - { name: oro_importexport.template_fixture }

    # Normalizer
    issues_bundle.importexport.normalizer.issue:
        class: IssuesBundle\ImportExport\Serializer\Normalizer\IssueNormalizer
        parent: oro_importexport.serializer.configurable_entity_normalizer
        tags:
            - { name: oro_importexport.normalizer }

    # Converter
    issues_bundle.importexport.data_converter.issue:
        parent: oro_importexport.data_converter.configurable

    issues_bundle.importexport.template_fixture.data_converter.issue:
        parent: oro_importexport.data_converter.template_fixture.configurable

    # Export Processor
    issues_bundle.importexport.export_processor.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
             - [setDataConverter, ['@issues_bundle.importexport.data_converter.issue']]
        tags:
            - { name: oro_importexport.processor, type: export, entity: %issues_bundle.import_export.entity%, alias: issues }

    issues_bundle.importexport.export_processor.template.issue:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@issues_bundle.importexport.template_fixture.data_converter.issue']]
        tags:
            - { name: oro_importexport.processor, type: export_template, entity: %issues_bundle.import_export.entity%, alias: issues }

    # Import Strategy
    issues_bundle.importexport.strategy.issues.add_or_replace:
        class: IssuesBundle\ImportExport\Strategy\IssueAddOrReplaceStrategy
        parent: oro_importexport.strategy.configurable_add_or_replace

    # Import processor
    issues_bundle.importexport.processor.issues:
        parent: oro_importexport.processor.import_abstract
        calls:
             - [setDataConverter, [@issues_bundle.importexport.data_converter.issue]]
             - [setStrategy, [@issues_bundle.importexport.strategy.issues.add_or_replace]]
        tags:
            - { name: oro_importexport.processor, type: import, entity: %issues_bundle.import_export.entity%, alias: issues.add_or_replace_issue }
            - { name: oro_importexport.processor, type: import_validation, entity: %issues_bundle.import_export.entity%, alias: issues.add_or_replace_issue }
