oro_menu_config:
    items:
        issues_tab:
            label: Issues
            uri:   '#'
            extras:
                position: 300
        issues_list:
            label: List issues
            route: issues.issues_index
            extras:
                routes: ['issues.issue_*']
        issues_add:
            label: Add new
            route: issues.issue_create
        issues_collaborated_recently:
            label: Collaborated recently
            route: issues.issues_collaborated_recently
            display: false
        issues_report:
            label: Issues
            route: issues.issues_index_report
            routeParameters:
                reportGroupName: issues
                reportName:      all_issues

    tree:
        application_menu:
            children:
                reports_tab:
                    children:
                        issues_report: ~
                issues_tab:
                    children:
                        issues_list: ~
                        issues_add: ~
                        issues_collaborated_recently: ~

oro_titles:
    issues.issues_index: ~
    issues.issue_view: "%%entity.code%%"
    issues.issue_create: ~
    issues.issue_update: "%%entity.code%% - Edit"