placeholders:
    view_content_data_additional_information:
        items:
            issues_user_view_issues_grid: ~

items:
    oro_send_email_button:
        template: IssuesBundle:Issue:activity/button.html.twig
        acl: oro_email_email_create
    oro_send_email_link:
        template: IssuesBundle:Issue:activity/link.html.twig
        acl: oro_email_email_create
    issues_user_view_issues_grid:
        template: IssuesBundle:User:userViewPageIssuesGrid.html.twig
        applicable: @oro_ui.placeholder.filter->isInstanceOf($entity$, %oro_user.entity.class%)