services:
    issues.repository.priority:
        class: IssuesBundle\Entity\Repository\PriorityRepository
        factory: ["@doctrine", getRepository]
        arguments:
            - "IssuesBundle:Priority"
