services:
    issues.model.collaboration:
        class: IssuesBundle\Model\Service\Collaboration
        arguments:
            - @doctrine.orm.entity_manager

    issues.workflow.action.remember_collaborant:
        class: IssuesBundle\Workflow\Action\RememberCollaboratorAction
        arguments:
            - @issues.model.collaboration
            - @security.token_storage
        tags:
            - { name: oro_workflow.action, alias: remember_collaborant }
