workflows:
    issue_resolving:
        label: 'Resolving Issue'
        entity: IssuesBundle\Entity\Issue
        steps_display_ordered: true
        start_step: opened
        steps:
            opened:
                label: 'Opened'
                order: 10
                allowed_transitions:
                    - start_progress
            in_progress:
                label: 'In progress'
                order: 20
                allowed_transitions:
                    - stop_progress
                    - resolve
            reopened:
                label: 'Reopened'
                order: 30
                allowed_transitions:
                    - start_progress
            resolved:
                label: 'Resolved'
                order: 40
                allowed_transitions:
                    - close
                    - reopen
            closed:
                label: 'Closed'
                order: 50
                allowed_transitions:
                    - reopen
                is_final: true
        attributes:
            resolution:
                label: issues.issue.resolution.label
                type: entity
                property_path: resolution
                options:
                    class: IssuesBundle\Entity\Resolution
        transitions:
            start_progress:
                is_start: true
                label: 'Start progress'
                step_to: in_progress
                transition_definition: start_progress_definition
            resolve:
                label: 'Resolve'
                step_to: resolved
                transition_definition: resolve_definition
            close:
                label: 'Close'
                step_to: closed
                transition_definition: close_definition
                form_options:
                    attribute_fields:
                        resolution:
                            options:
                                required: true
            reopen:
                label: 'Reopen'
                step_to: reopened
                transition_definition: reopen_definition
            stop_progress:
                label: 'Stop progress'
                step_to: opened
                transition_definition: stop_progress_definition
        transition_definitions:
            start_progress_definition:
                post_actions:
                    - @remember_collaborant: []
            resolve_definition:
                post_actions:
                    - @remember_collaborant: []
            close_definition:
                post_actions:
                    - @remember_collaborant: []
                    - @set_resolution:
                        attribute: $resolution
                        data:
                            name: $resolution
            reopen_definition:
                post_actions:
                    - @remember_collaborant: []
            stop_progress_definition:
                post_actions:
                    - @remember_collaborant: []